spring:
  application:
    name: Tic-tac-toe game engine service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jackson:
    mapper:
      accept-case-insensitive-enums: true
server:
  port: 8081
springdoc:
  swagger-ui.path: /swagger
